In [3]:
import numpy as np
from termcolor import colored

In [6]:
g = np.diag([1.0, -1.0, -1.0, -1.0])

# Single boosts
beta1 = 0.6
beta2 = 0.6

gamma1 = 1.0 / np.sqrt(1.0 - beta1**2)
gamma2 = 1.0 / np.sqrt(1.0 - beta2**2)

L1 = np.array([
    [gamma1, -beta1*gamma1, 0.0, 0.0],
    [-beta1*gamma1, gamma1, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0],
], dtype=float)

print(colored("L1 =\n", "blue"), np.round(L1, 4))
print(colored("Metric check L1:\n", "green"), np.round(L1.T @ g @ L1, 4))
print(colored("Determinant check L1:", "yellow"), np.round(np.linalg.det(L1), 4))


L2 = np.array([
    [gamma2, 0.0, -beta2*gamma2, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [-beta2*gamma2, 0.0, gamma2, 0.0],
    [0.0, 0.0, 0.0, 1.0],
], dtype=float)

print(colored("L2 =\n", "blue"), np.round(L2, 4))
print(colored("Metric check L2:\n", "green"), np.round(L2.T @ g @ L2, 4))
print(colored("Determinant check L2:", "yellow"), np.round(np.linalg.det(L2), 4))

# Combined boost: L12 = L2 @ L1
L12 = L2 @ L1

print(colored("L12 =\n", "blue"), np.round(L12, 4))
print(colored("Metric check L12:\n", "green"), np.round(L12.T @ g @ L12, 4))
print(colored("Determinant check L12:\n", "yellow"), np.round(np.linalg.det(L12), 4))

# Single boost along beta3 = (0.6, 0.6, 0)
beta3 = np.array([0.6, 0.6/gamma1, 0.0], dtype=float)
beta3_sq = np.dot(beta3, beta3)
gamma3 = 1.0 / np.sqrt(1.0 - beta3_sq)

L3 = np.array([
    [gamma3, -beta3[0]*gamma3, -beta3[1]*gamma3, 0.0],
    [-beta3[0]*gamma3, 1.0 + (gamma3 - 1.0) * (beta3[0]**2 / beta3_sq), (gamma3 - 1.0) * (beta3[0]*beta3[1] / beta3_sq), 0.0],
    [-beta3[1]*gamma3, (gamma3 - 1.0) * (beta3[0]*beta3[1] / beta3_sq), 1.0 + (gamma3 - 1.0) * (beta3[1]**2 / beta3_sq), 0.0],
    [0.0, 0.0, 0.0, 1.0],
], dtype=float)

print(colored("L3 =\n", "blue"), np.round(L3, 4))
print(colored("Metric check L3:\n", "green"), np.round(L3.T @ g @ L3, 4))
print(colored("Determinant check L3:", "yellow"), np.round(np.linalg.det(L3), 4))
print(colored("L12 == L3 ?", "red"), np.allclose(L12, L3))

L1 =
 [[ 1.25 -0.75  0.    0.  ]
 [-0.75  1.25  0.    0.  ]
 [ 0.    0.    1.    0.  ]
 [ 0.    0.    0.    1.  ]]
Metric check L1:
 [[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
Determinant check L1: 1.0
L2 =
 [[ 1.25  0.   -0.75  0.  ]
 [ 0.    1.    0.    0.  ]
 [-0.75  0.    1.25  0.  ]
 [ 0.    0.    0.    1.  ]]
Metric check L2:
 [[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
Determinant check L2: 1.0
L12 =
 [[ 1.5625 -0.9375 -0.75    0.    ]
 [-0.75    1.25    0.      0.    ]
 [-0.9375  0.5625  1.25    0.    ]
 [ 0.      0.      0.      1.    ]]
Metric check L12:
 [[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
Determinant check L12:
 1.0
L3 =
 [[ 1.5625 -0.9375 -0.75    0.    ]
 [-0.9375  1.343   0.2744  0.    ]
 [-0.75    0.2744  1.2195  0.    ]
 [ 0.      0.      0.      1.    ]]
Metric check L3:
 [[ 1.  0. -0.  0.]
 [ 0. -1.  0.  0.]
 [-0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
Determinant ch